version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_CLICKHOUSE_HOST=clickhouse
      - REACT_APP_CLICKHOUSE_PORT=9000
      - REACT_APP_CLICKHOUSE_DATABASE=default
      - REACT_APP_CLICKHOUSE_USER=default
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DATABASE=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    depends_on:
      - clickhouse
    networks:
      - app-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"  # Native protocol
      - "8123:8123"  # HTTP interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - app-network

volumes:
  clickhouse_data:
  clickhouse_logs:

networks:
  app-network:
    driver: bridge 